queueServiceURL: "amqp://rabbitmq:rabbitmq@localhost:5672/magnetico"
queueServicePersistsDatabaseURL: "postgres://magnetico:magnetico@localhost:5432/magnetico?sslmode=disable"
databaseURL: "amqp://rabbitmq:rabbitmq@localhost:5672/magnetico"
indexerAddrs: "0.0.0.0:0"
indexerMaxNeighbors: 600
leechMaxN: 700
maxRPS: 600
bootstrappingNodes: "dht.libtorrent.org:25401,dht.transmissionbt.com:6881,router.bittorrent.com:6881"
bootstrapNodesSelfPort: true
filterNodesCIDRs: ""
addr: "0.0.0.0:58965"
cred: ""
runDaemon: true
runWeb: false
runStorage: true
